import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Roboto } from "next/font/google";
import MusicTrail from "@/components/MusicTrail";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "700"], // regular + bold
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased min-h-screen bg-gray-100 dark:bg-gray-950 text-black dark:text-white flex flex-col items-center`}
      >
        <MusicTrail/>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
